//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecms.Biz.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complaint
    {
        public Complaint()
        {
            this.ComplaintDetails = new HashSet<ComplaintDetail>();
        }
    
        public int Id { get; set; }
        public string ComplaintsNo { get; set; }
        public Nullable<int> CreatedUser { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CloseUser { get; set; }
        public Nullable<System.DateTime> ComplaintsDate { get; set; }
        public Nullable<System.DateTime> LastModifyDate { get; set; }
        public string Title { get; set; }
        public string ContentComplaints { get; set; }
        public Nullable<int> ReceiverComplaintsId { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public string Remark { get; set; }
    
        public virtual ICollection<ComplaintDetail> ComplaintDetails { get; set; }
    }
}
