//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecms.Biz.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigBusiness
    {
        public ConfigBusiness()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int ConfigBusinessId { get; set; }
        public Nullable<int> CustomerTypeId { get; set; }
        public Nullable<int> OrderTypeId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string BusinessCode { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<double> ConfigValue { get; set; }
        public Nullable<int> WebsiteId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Remark { get; set; }
        public Nullable<double> fromQuantity { get; set; }
        public Nullable<double> toQuantity { get; set; }
        public string Unit { get; set; }
    
        public virtual Mst_Business Mst_Business { get; set; }
        public virtual Country Country { get; set; }
        public virtual CustomerType CustomerType { get; set; }
        public virtual OrderType OrderType { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
