//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecms.Biz.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Invoices = new HashSet<Invoice>();
            this.Orders = new HashSet<Order>();
            this.Inv_StockInOut = new HashSet<Inv_StockInOut>();
            this.Rpt_DeliverlyConfirmPrint = new HashSet<Rpt_DeliverlyConfirmPrint>();
        }
    
        public int CustomerId { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public Nullable<double> Balance { get; set; }
        public Nullable<int> Status { get; set; }
        public string Mobile { get; set; }
        public Nullable<int> CityId { get; set; }
        public string ContactAccount { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastDateModify { get; set; }
        public Nullable<int> CustomerTypeId { get; set; }
        public string UserCode { get; set; }
        public string DeliveryName { get; set; }
        public string DeliveryMobile { get; set; }
        public string DeliveryEmail { get; set; }
        public string DeliveryAddress { get; set; }
        public string CustomerCodeDelivery { get; set; }
        public string EmployeeCode { get; set; }
    
        public virtual CustomerType CustomerType { get; set; }
        public virtual Sys_User Sys_User { get; set; }
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<Inv_StockInOut> Inv_StockInOut { get; set; }
        public virtual ICollection<Rpt_DeliverlyConfirmPrint> Rpt_DeliverlyConfirmPrint { get; set; }
    }
}
