//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecms.Biz.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_StockInOutDetail
    {
        public int Id { get; set; }
        public Nullable<int> StockInOutId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> Price { get; set; }
        public string Remark { get; set; }
        public string Serial { get; set; }
    
        public virtual Inv_StockInOut Inv_StockInOut { get; set; }
        public virtual Product Product { get; set; }
    }
}
