//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecms.Biz.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public Invoice()
        {
            this.InvoiceDetails = new HashSet<InvoiceDetail>();
            this.CustomerBalanceHistories = new HashSet<CustomerBalanceHistory>();
        }
    
        public int InvoiceId { get; set; }
        public string InvoiceCode { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> SubCustomerId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public string BusinessCode { get; set; }
        public Nullable<int> BankId { get; set; }
        public string FromAccount { get; set; }
        public string Remark { get; set; }
        public Nullable<int> Status { get; set; }
        public string ReplyContent { get; set; }
        public Nullable<int> InvoiceRefId { get; set; }
        public Nullable<System.DateTime> LastDateModify { get; set; }
        public string Description { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Mst_Business Mst_Business { get; set; }
        public virtual ICollection<InvoiceDetail> InvoiceDetails { get; set; }
        public virtual Order Order { get; set; }
        public virtual ICollection<CustomerBalanceHistory> CustomerBalanceHistories { get; set; }
    }
}
