//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecms.Biz.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_Business
    {
        public Mst_Business()
        {
            this.Invoices = new HashSet<Invoice>();
            this.ConfigBusinesses = new HashSet<ConfigBusiness>();
        }
    
        public string BusinessCode { get; set; }
        public string BusinessName { get; set; }
        public string Description { get; set; }
        public Nullable<double> DefaultValue { get; set; }
        public Nullable<int> Type { get; set; }
    
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual ICollection<ConfigBusiness> ConfigBusinesses { get; set; }
    }
}
