//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecms.Biz.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_VisaAccount
    {
        public Mst_VisaAccount()
        {
            this.OrderOutbounds = new HashSet<OrderOutbound>();
        }
    
        public int VisaId { get; set; }
        public string VisaNo { get; set; }
        public string Remark { get; set; }
    
        public virtual ICollection<OrderOutbound> OrderOutbounds { get; set; }
    }
}
