//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecms.Biz.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public News()
        {
            this.News_Comment = new HashSet<News_Comment>();
            this.News1 = new HashSet<News>();
        }
    
        public int NewsId { get; set; }
        public string Title { get; set; }
        public string ShortContent { get; set; }
        public string NewsContent { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<bool> Published { get; set; }
        public string NewsImage { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> WebsiteId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreateUser { get; set; }
        public string Email { get; set; }
        public string FullName { get; set; }
        public Nullable<bool> AllowDelete { get; set; }
    
        public virtual ICollection<News_Comment> News_Comment { get; set; }
        public virtual ICollection<News> News1 { get; set; }
        public virtual News News2 { get; set; }
    }
}
