//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecms.Biz.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class News_Comment
    {
        public int CommentId { get; set; }
        public string Comment { get; set; }
        public Nullable<int> NewsId { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual News News { get; set; }
    }
}
