//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecms.Biz.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderOutbound
    {
        public OrderOutbound()
        {
            this.OrderOutboundDetails = new HashSet<OrderOutboundDetail>();
            this.OrderOutboundHistories = new HashSet<OrderOutboundHistory>();
        }
    
        public int OrderOutboundId { get; set; }
        public string OrderOutboundNo { get; set; }
        public string TrackingNo { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> WebsiteAccountId { get; set; }
        public string UserCreate { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> DeliveryUSADate { get; set; }
        public Nullable<System.DateTime> DeliveryVNDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<int> WebsiteAccountVisaId { get; set; }
        public Nullable<int> VisaId { get; set; }
    
        public virtual Sys_User Sys_User { get; set; }
        public virtual ICollection<OrderOutboundDetail> OrderOutboundDetails { get; set; }
        public virtual ICollection<OrderOutboundHistory> OrderOutboundHistories { get; set; }
        public virtual Mst_VisaAccount Mst_VisaAccount { get; set; }
        public virtual WebsiteAccount WebsiteAccount { get; set; }
    }
}
