//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecms.Biz.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.Invoices = new HashSet<Invoice>();
            this.OrderHistories = new HashSet<OrderHistory>();
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int OrderId { get; set; }
        public string OrderNo { get; set; }
        public string OrderOutboundNo { get; set; }
        public string TrackingNo { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<System.DateTime> NeedDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string DeliveryName { get; set; }
        public string DeliveryMobile { get; set; }
        public string DeliveryEmail { get; set; }
        public string DeliveryAddress { get; set; }
        public string ContactChannel { get; set; }
        public Nullable<int> OrderStatus { get; set; }
        public Nullable<double> AmountDeposit { get; set; }
        public Nullable<double> AmountRemain { get; set; }
        public Nullable<int> OrderTypeId { get; set; }
        public Nullable<bool> IsInsurance { get; set; }
        public string Remark { get; set; }
        public string OrderNoDelivery { get; set; }
        public string CustomerCodeDelivery { get; set; }
        public Nullable<int> ConfigRateId { get; set; }
        public Nullable<System.DateTime> DateToUsa { get; set; }
        public string EmployeeCode { get; set; }
        public Nullable<System.DateTime> ConfirmDate { get; set; }
        public Nullable<int> DayAllowedDelay { get; set; }
        public string CalFeeDelay { get; set; }
        public Nullable<double> AmountCalFeeDelay { get; set; }
        public Nullable<double> AmountFeeDelay { get; set; }
        public Nullable<System.DateTime> CalDateFeeDelay { get; set; }
        public Nullable<double> FeeDelay { get; set; }
        public string IsCalFeeDelay { get; set; }
        public string CreateUser { get; set; }
        public string UserModify { get; set; }
        public string Description { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual OrderType OrderType { get; set; }
        public virtual ICollection<OrderHistory> OrderHistories { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
