//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecms.Biz.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public OrderDetail()
        {
            this.OrderOutboundDetails = new HashSet<OrderOutboundDetail>();
            this.Rpt_DeliverlyCPDetail = new HashSet<Rpt_DeliverlyCPDetail>();
        }
    
        public int OrderDetailId { get; set; }
        public int OrderId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> PriceWeb { get; set; }
        public Nullable<double> PriceWebOff { get; set; }
        public Nullable<int> TaxUsaConfigId { get; set; }
        public Nullable<int> InsuaranceConfigId { get; set; }
        public Nullable<int> ShipConfigId { get; set; }
        public Nullable<double> ShipModified { get; set; }
        public Nullable<double> ShipUSAVN { get; set; }
        public Nullable<double> ShipUSA { get; set; }
        public Nullable<double> Surcharge { get; set; }
        public Nullable<double> DeclarePrice { get; set; }
        public Nullable<int> EffortConfigId { get; set; }
        public Nullable<double> EffortModified { get; set; }
        public string ImageUrl { get; set; }
        public string ProductLink { get; set; }
        public string Size { get; set; }
        public string Color { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<int> WebsiteId { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> DetailStatus { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string TrackingNo { get; set; }
        public string OrderNoDelivery { get; set; }
        public Nullable<System.DateTime> DateToUsa { get; set; }
        public Nullable<int> DeliveryStatus { get; set; }
        public Nullable<System.DateTime> DeliveryVNDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string LotPrice { get; set; }
        public string DetailCode { get; set; }
        public Nullable<int> RateCountryId { get; set; }
        public string Shop { get; set; }
        public string Remark { get; set; }
    
        public virtual ConfigBusiness ConfigBusiness { get; set; }
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
        public virtual WebsiteLink WebsiteLink { get; set; }
        public virtual ICollection<OrderOutboundDetail> OrderOutboundDetails { get; set; }
        public virtual ICollection<Rpt_DeliverlyCPDetail> Rpt_DeliverlyCPDetail { get; set; }
    }
}
