//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecms.Biz.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderOutboundDetail
    {
        public int OrderOutboundDetailId { get; set; }
        public int OrderOutboundId { get; set; }
        public Nullable<int> OrderDetailId { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> Price { get; set; }
    
        public virtual OrderOutbound OrderOutbound { get; set; }
        public virtual OrderDetail OrderDetail { get; set; }
    }
}
