//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecms.Biz.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Inv_Goods = new HashSet<Inv_Goods>();
            this.Inv_StockBalance = new HashSet<Inv_StockBalance>();
            this.Inv_StockInOutDetail = new HashSet<Inv_StockInOutDetail>();
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int ProductId { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public Nullable<double> ProductValue { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Size { get; set; }
        public string Image { get; set; }
        public Nullable<bool> Published { get; set; }
        public string Tag { get; set; }
        public string ShortDescription { get; set; }
        public string Description { get; set; }
        public Nullable<int> VendorId { get; set; }
        public string Orginal { get; set; }
        public Nullable<double> Balance { get; set; }
        public string BestSale { get; set; }
        public Nullable<double> ProductSaleValue { get; set; }
        public Nullable<int> PPriority { get; set; }
        public string ProductType { get; set; }
        public string ProductLable { get; set; }
        public Nullable<System.DateTime> LastDateModify { get; set; }
        public Nullable<int> ProductStatus { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<Inv_Goods> Inv_Goods { get; set; }
        public virtual Vendor Vendor { get; set; }
        public virtual ICollection<Inv_StockBalance> Inv_StockBalance { get; set; }
        public virtual ICollection<Inv_StockInOutDetail> Inv_StockInOutDetail { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
