//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecms.Biz.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rpt_DeliverlyCPDetail
    {
        public int CPDetailId { get; set; }
        public Nullable<int> RptDeliverlyId { get; set; }
        public Nullable<int> OrderDetailId { get; set; }
        public string Remark { get; set; }
    
        public virtual Rpt_DeliverlyConfirmPrint Rpt_DeliverlyConfirmPrint { get; set; }
        public virtual OrderDetail OrderDetail { get; set; }
    }
}
