//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecms.Biz.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Object
    {
        public Sys_Object()
        {
            this.Sys_MapGroupObject = new HashSet<Sys_MapGroupObject>();
        }
    
        public string ObjectCode { get; set; }
        public string ObjectName { get; set; }
        public string ObjectType { get; set; }
        public string ObjectTemplate { get; set; }
        public string ParentObjectCode { get; set; }
        public string FlagActive { get; set; }
        public Nullable<int> OPriority { get; set; }
    
        public virtual ICollection<Sys_MapGroupObject> Sys_MapGroupObject { get; set; }
    }
}
