//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecms.Biz.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_User
    {
        public Sys_User()
        {
            this.Sys_MapUserGroup = new HashSet<Sys_MapUserGroup>();
            this.Customers = new HashSet<Customer>();
            this.OrderOutbounds = new HashSet<OrderOutbound>();
        }
    
        public string UserCode { get; set; }
        public string UserName { get; set; }
        public string UserPassword { get; set; }
        public string FlagActive { get; set; }
        public string Position { get; set; }
        public string Remark { get; set; }
        public string FlagAdmin { get; set; }
        public string Email { get; set; }
        public string SupperAdmin { get; set; }
    
        public virtual ICollection<Sys_MapUserGroup> Sys_MapUserGroup { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual ICollection<OrderOutbound> OrderOutbounds { get; set; }
    }
}
