//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecms.Biz.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebsiteAccount
    {
        public WebsiteAccount()
        {
            this.OrderOutbounds = new HashSet<OrderOutbound>();
            this.WebsiteAccountVisas = new HashSet<WebsiteAccountVisa>();
        }
    
        public int WebsiteAccountId { get; set; }
        public Nullable<int> WebsiteId { get; set; }
        public string AccountWebsiteNo { get; set; }
        public string Website { get; set; }
        public string Remark { get; set; }
    
        public virtual ICollection<OrderOutbound> OrderOutbounds { get; set; }
        public virtual WebsiteLink WebsiteLink { get; set; }
        public virtual ICollection<WebsiteAccountVisa> WebsiteAccountVisas { get; set; }
    }
}
