//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecms.Biz.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebsiteAccountVisa
    {
        public int WebsiteAccountVisaId { get; set; }
        public Nullable<int> WebsiteAccountId { get; set; }
        public string VisaNo { get; set; }
    
        public virtual WebsiteAccount WebsiteAccount { get; set; }
    }
}
